name: Install Edith

on:
  push:
    branches:
      - main

jobs:
  edith-install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Nutter Tools MM FS client
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: laneone/edith-images:nutter_tools_mm_fs_latest
        
    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          curl -sSL https://github.com/theycallmeloki/edith-cli/raw/main/edith -o edith
          chmod +x edith
          sudo apt-get update
          sudo apt-get install -y python3-pip nginx jq
          sudo python3 -m pip install ansible kubernetes jmespath
          sudo ./edith install
    
