name: Install Edith

on:
  push:
    branches:
      - main

jobs:
  install-edith:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          curl -sSL https://github.com/theycallmeloki/edith-cli/raw/main/edith -o edith
          chmod +x edith
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo python3 -m pip install ansible
          ansible-galaxy install gantsign.minikube --force
          sudo ./edith install